Import('env', 'bindir');

minidlna_sources = [
    "minidlna.c", "upnphttp.c", "upnpdescgen.c", "upnpsoap.c",
    "upnpreplyparse.c", "minixml.c",
    "getifaddr.c", "daemonize.c", "upnpglobalvars.c",
    "options.c", "minissdp.c", "uuid.c", "upnpevents.c",
    "sql.c", "utils.c", "metadata.c", "scanner.c", "inotify.c",
    "tivo_utils.c", "tivo_beacon.c", "tivo_commands.c",
    "tagutils/textutils.c", "tagutils/misc.c", "tagutils/tagutils.c",
    "playlist.c", "image_utils.c", "albumart.c", "log.c"
]
testupnpdescgen_sources = [ "testupnpdescgen.c", "upnpdescgen.c" ]

minidlna = env.Program(target = "minidlna", source = minidlna_sources);
testupnpdescgen = env.Program(target = "testupnpdescgen", source = testupnpdescgen_sources);

Return('minidlna', 'testupnpdescgen')
